apiVersion: v1
kind: Service
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http-alertmanager
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: http-alertmanager-80
      port: 80
      targetPort: 80
      nodePort: 30081
  selector:
    app.kubernetes.io/name: alertmanager

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http-prometheus-8081
      port: 8081
      targetPort: 8081
      nodePort: 30082
    - name: http-prometheus-80
      port: 80
      targetPort: 80
      nodePort: 30083
  selector:
    app.kubernetes.io/name: prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: thanos-frontend-query
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http-frontend-query
      port: 8082
      targetPort: 9090
      nodePort: 30084
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: storegateway

---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http-query-8085
      port: 8085
      targetPort: 9090
      nodePort: 30085
    - name: grpc-query-8086
      port: 8086
      targetPort: 8086
      nodePort: 30086
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: query

---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query-grpc
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: grpc-query-grpc
      port: 8088
      targetPort: 10901
      nodePort: 30087
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: query

---
apiVersion: v1
kind: Service
metadata:
  name: thanos-receiver
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http-receiver
      port: 8092
      targetPort: 8092
      nodePort: 30088
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: receive

---
apiVersion: v1
kind: Service
metadata:
  name: thanos-storage-gateway-query
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http-storage-query
      port: 8101
      targetPort: 9090
      nodePort: 30089
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: storegateway

---
apiVersion: v1
kind: Service
metadata:
  name: thanos-storage-gateway-query-grpc
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: grpc-storage-query-grpc
      port: 8103
      targetPort: 10901
      nodePort: 30090
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/component: storegateway
