type: S3
config:
  bucket: "${S3_BUCKET_NAME}"
  endpoint: "s3.eu-west-2.amazonaws.com"
  access_key: "${AWS_ACCESS_KEY_ID}"
  secret_key: "${AWS_SECRET_ACCESS_KEY}"
  region: "eu-west-2"
  insecure: false