apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
spec:
  replicas: 1
  serviceName: alertmanager
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: bitnami/alertmanager:latest
        ports:
        - containerPort: 9093
          name: web
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  ports:
  - protocol: TCP
    port: 9093
    targetPort: web
