apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-storage-gateway
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-storage-gateway
  template:
    metadata:
      labels:
        app: thanos-storage-gateway
    spec:
      containers:
      - name: thanos-storage-gateway
        image: bitnami/thanos:latest
        args:
          - store
          - "--objstore.config-file=/etc/config/s3-config.yaml"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: s3-config
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-storage-gateway
  namespace: monitoring
spec:
  selector:
    app: thanos-storage-gateway
  ports:
  - name: http
    port: 8100
    targetPort: http
  type: NodePort
