apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-storage-gateway
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-storage-gateway
  template:
    metadata:
      labels:
        app: thanos-storage-gateway
    spec:
      containers:
      - name: thanos-storage-gateway
        image: bitnami/thanos:latest
        args:
          - store
          - "--objstore.config-file=/etc/config/s3-config.yaml"
          - "--data-dir=/data"  # Set the data directory to use the mounted volume
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
          - name: data-volume
            mountPath: /data  # Mount the writable volume here
      volumes:
      - name: config-volume
        configMap:
          name: s3-config
      - name: data-volume
        emptyDir: {}  # Temporary writable directory for testing
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-storage-gateway
  namespace: monitoring
spec:
  selector:
    app: thanos-storage-gateway
  ports:
  - name: http
    port: 8100
    targetPort: http
  type: NodePort
