apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-remote-write
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-remote-write
  template:
    metadata:
      labels:
        app: thanos-remote-write
    spec:
      containers:
      - name: thanos-sidecar
        image: bitnami/thanos:latest
        args:
          - sidecar
        ports:
        - name: grpc
          containerPort: 10901
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-remote-write
  namespace: monitoring
spec:
  selector:
    app: thanos-remote-write
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  type: NodePort
